// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://occvvkqjvdypnyumpqga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jY3Z2a3FqdmR5cG55dW1wcWdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NTcxOTIsImV4cCI6MjA2ODAzMzE5Mn0.ThLDJG8bhoPexdimn8FePJ4sQ2s1OTcOApnYNXsOveE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});